### ISSUE TITLE
script isn't working

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/batchwords#1]
maybe i'm misunderstanding how it's supposed to work, but following these steps, i get a file with only the header:
a) run python batchwords.py
b) click load and choose the csv_files folder
c) load the word list in the input folder
d) click select (not sure how what's highlighted or not maps on to selected/cleared/etc, something wonky there). it says 'files selected'. i played around with this, cleared, selected, etc. if you just click one file and then select you get some errors callback to line 1470, e.g. 
TypeError: list indices must be integers, not str
('0', '1', '2')

e) click 'both'
f) click export, and name it 

produces file with a header but not content, I think because it didn't actual select any files even though it says 'files selected' (indeed after you clear the list and then click select it says 'files selected' and the terminal says

**Comment by andreiamatuni** [comment]
You need to click the files in the box first and then after all the ones you want are blue, click "Select". The rest of the steps you're going through are right. I pushed a commit that fixes a few bugs that may have been the root of the Type error, but were distinct bugs aside from that.

**Comment by ebergelson** [comment]
nope, that doesn't result in the files getting selected (no green 'files selected' when i make them all blue and click select), and in the terminal i get:
python batchwords.py
['07_06_coderSM_video_checkSK.csv']
['07_06_coderSM_video_checkSK.csv', '08_06_coderGC_audio_checkEB.csv']
['07_06_coderSM_video_checkSK.csv', '08_06_coderGC_audio_checkEB.csv', '08_06_coderVL_video_checkSM.csv']
['07_06_coderSM_video_checkSK.csv', '08_06_coderGC_audio_checkEB.csv', '08_06_coderVL_video_checkSM.csv', '09_06_coderAM_video_checkSM.csv']('0',)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in **call**
    return self.func(*args)
  File "batchwords.py", line 153, in select_files
    print self.all_csv_files[selection]
TypeError: list indices must be integers, not str
