### ISSUE TITLE
display gui too narrow to see file names

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/batchwords#2]
![screen shot 2015-05-13 at 2 05 34 pm](https://cloud.githubusercontent.com/assets/11085620/7617459/2b84083a-f979-11e4-9b15-8a8d6f92871a.png)

can be fixed by removing relative path or widening box in gui

**Comment by andreiamatuni** [comment]
should be fixed with e53d13fd56b66317a98b287fcbb3e1ed579e8878
